#!/bin/bash

# parsing configuration
config="$(mktemp)"
cat > "$config"

resources="$(jshon -e 'resources' -u < "$config")"
judge="$(jshon -e 'judge' -u < "$config")"
workdir="$(jshon -e 'workdir' -u < "$config")"

# Prepare to compile
compiledir=$(mktemp -d)
cd $compiledir
cp -r $resources/* .
cat "$(jshon -e 'source' -u < "$config")" > "solution.cs"

# Compiling solution with tests
compileresult="$(mktemp)"
csc -reference:/home/runner/.nuget/packages/nunit/3.12.0/lib/net40/nunit.framework.dll -out:$workdir/testproject.dll -target:library solution.cs tests.cs > $compileresult

if [ $? -ne 0 ]; then
    jshon -s "start-judgement"  -i "command" <<< "{}"
    message="<pre>$(cat $compileresult | tail -n +4)</pre>"
    jshon -s "append-message" -i "command" -n {} -s "html" -i "format" -s "$message" -i "description" -i "message"<<< "{}"
    jshon -s "close-judgement"  -i "command" -n {} -s "compilation error" -i "enum" -i "status" <<< "{}"
    exit 0
fi

# Copy testing framework
cp /home/runner/.nuget/packages/nunit/3.12.0/lib/net40/nunit.framework.dll $workdir/nunit.framework.dll

# Execute the tests
cd $workdir
rm -r $compiledir
mono $judge/bin/judge-csharp.exe testproject.dll