#!/bin/bash

# parsing configuration
config="$(mktemp)"
cat > "$config"

resources="$(jshon -e 'resources' -u < "$config")"
judge="$(jshon -e 'judge' -u < "$config")"
workdir="$(jshon -e 'workdir' -u < "$config")"

# Prepare to compile
compiledir=$(mktemp -d)
cd $compiledir
cp -r $resources/* .
cp $judge/solution.csproj .
cp -r $judge/lib .
cat "$(jshon -e 'source' -u < "$config")" > "solution.cs"

# Compiling solution with tests
compileresult="$(mktemp)"
dotnet build solution.csproj > $compileresult

if [ $? -ne 0 ]; then
    jshon -s "start-judgement"  -i "command" <<< "{}"
    message="<pre>$(cat $compileresult | tail -n +4)</pre>"
    jshon -s "append-message" -i "command" -n {} -s "html" -i "format" -s "$message" -i "description" -i "message"<<< "{}"
    jshon -s "close-judgement" -i "command" -n false -i "accepted" -n {} -s "compilation error" -i "enum" -i "status" <<< "{}"
    exit 0
fi

mv solution.dll $workdir

# Copy testing framework
cp -r $judge/lib/* $workdir

# Execute the tests
cd $workdir
rm -r $compiledir

$judge/bin/judge-csharp solution.dll

